spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8761

logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: TRACE
